name: Test suite CI run

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**
  workflow_dispatch: {}

jobs:
  python_test_suite:
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, windows-latest]
        include:
          - tox_env: "37"
            python_version: "3.7"
          - tox_env: "38"
            python_version: "3.8"
          - tox_env: "39"
            python_version: "3.9"
          - tox_env: "310"
            python_version: "3.10"
      max-parallel: 4
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout optmath and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python interpreter
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        architecture: "x64"
        cache: pip

    - name: Install tox
      run: python -m pip install tox

    - name: Set up Python interpreter
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python_version }}
        architecture: "x64"
        cache: pip

    - name: Run Python test suite
      run: tox -e py${{ matrix.tox_env }} -vv
